name: csv_localizations
description: A minimal CSV localization package built on LocalizationsDelegate.
version: 1.6.0
homepage: https://github.com/erf/csv_localizations

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  csv: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
