name: csv_localizations
description: A minimal CSV localization package for Flutter built on LocalizationsDelegate.
version: 0.4.0
homepage: https://github.com/erf/csv_localizations

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  csv: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
