name: csv_localizations
description: CSV localization package built on LocalizationsDelegate
version: 0.7.0
homepage: https://github.com/erf/csv_localizations

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  csv: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
